### ISSUE TITLE
FileNotFoundException: /doclet.css (Permission denied)

### ISSUE THREAD

**Issue by antonpiatek** [FroMage/jax-doclets#39]
I am getting a file not found exception (permission denied) for /doclet.css using the 0.9 jar download and trying to run the jaxb doclets from ant:
<target  description="Run the JAXB doclet" name="doc-jaxb">
     <javadoc doclet="com.lunatech.doclets.jax.jaxb.JAXBDoclet" docletpath="jaxdoclet/jax-doclets-0.9.0.jar" sourcepath="servletsrc">
      <package name="com.*"/>
     </javadoc>
    </target>

I get the following stack.
  [javadoc] javadoc: error - In doclet class com.lunatech.doclets.jax.jaxb.JAXBDoclet,  method start has thrown an exception java.lang.reflect.InvocationTargetException
  [javadoc] java.lang.RuntimeException: java.io.FileNotFoundException: /doclet.css (Permission denied)
  [javadoc]     at com.lunatech.doclets.jax.Utils.copyResource(Utils.java:453)
  [javadoc]     at com.lunatech.doclets.jax.Utils.copyResources(Utils.java:438)
  [javadoc]     at com.lunatech.doclets.jax.jaxb.JAXBDoclet.start(JAXBDoclet.java:110)
  [javadoc]     at com.lunatech.doclets.jax.jaxb.JAXBDoclet.start(JAXBDoclet.java:93)
  [javadoc]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  [javadoc]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)
  [javadoc]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  [javadoc]     at java.lang.reflect.Method.invoke(Method.java:600)
  [javadoc]     at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:269)
  [javadoc]     at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:143)
  [javadoc]     at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:340)
  [javadoc]     at com.sun.tools.javadoc.Start.begin(Start.java:128)
  [javadoc]     at com.sun.tools.javadoc.Main.execute(Main.java:41)
  [javadoc]     at com.sun.tools.javadoc.Main.main(Main.java:31)
  [javadoc] Caused by: java.io.FileNotFoundException: /doclet.css (Permission denied)
  [javadoc]     at java.io.FileOutputStream.open(Native Method)
  [javadoc]     at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
  [javadoc]     at java.io.FileOutputStream.<init>(FileOutputStream.java:145)
  [javadoc]     at com.lunatech.doclets.jax.Utils.copyResource(Utils.java:443)

The jar file does contain the file, so I don't quite know why it can't open it. The jar is +rw for my userid.

**Comment by antonpiatek** [comment]
Setting a destdir="output/" on the javadoc ant task seems to have solved it - I'm not sure where it was trying to write, but setting a path explicitly has resolved the issue for me.
