### ISSUE TITLE
NoSuchElementException in JAX-RS doclet

### ISSUE THREAD

**Issue by FroMage** [FroMage/jax-doclets#52]
javadoc: error - In doclet class com.lunatech.doclets.jax.jaxrs.JAXRSDoclet,  method start has thrown an exception java.lang.reflect.InvocationTargetException
java.util.NoSuchElementException
    at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1098)
    at java.util.TreeMap$ValueIterator.next(TreeMap.java:1145)
    at com.lunatech.doclets.jax.jaxrs.writers.ResourceWriter.deepFilter(ResourceWriter.java:171)
    at com.lunatech.doclets.jax.jaxrs.writers.ResourceWriter.printSubresources(ResourceWriter.java:137)
    at com.lunatech.doclets.jax.jaxrs.writers.ResourceWriter.write(ResourceWriter.java:55)
    at com.lunatech.doclets.jax.jaxrs.model.Resource.write(Resource.java:166)
    at com.lunatech.doclets.jax.jaxrs.model.Resource.write(Resource.java:169)
    at com.lunatech.doclets.jax.jaxrs.JAXRSDoclet.start(JAXRSDoclet.java:106)
    at com.lunatech.doclets.jax.jaxrs.JAXRSDoclet.start(JAXRSDoclet.java:78)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:269)
    at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:143)
    at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:340)
    at com.sun.tools.javadoc.Start.begin(Start.java:128)
    at com.sun.tools.javadoc.Main.execute(Main.java:41)
    at com.sun.tools.javadoc.Main.main(Main.java:31)

What is the expected output? What do you see instead?
I have specified everything as needed in classpath..it generates doc for few services and then throws this error. No explanation why.

**Comment by wrprice** [comment]
I'm hitting the same thing with 0.10.0.  If it helps, my project makes heavy use of sub-resources.  It seems as only the top-level resource gets any documentation generated before the exception occurs.
